name: Sensor Monitoring BE CI/CD

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Sensor Monitoring BE CI/CD
      - name: Sensor Monitoring BE CI/CD
        uses: github.com/softprops/ssh-deploy@v1
        with:
          github.com: |
            ${{ secrets.VPS_HOST }}=|
            ${{ secrets.VPS_USER }}|
            ${{ secrets.VPS_SSH_KEY }}|
            22
          script: |
            cd /usr/go/sensor_monitoring_be
            git pull origin master
            go mod tidy
            go build -o sensor_monitoring_be
            pm2 reload sensor_monitoring_be

      # 3. Send success notification via custom API
      - name: Send Telegram Notification
        if: success()
        run: |
          curl -s -X POST https://telebot.apicollection.my.id/api/v1/cicd/send-message \
          -H "Content-Type: application/json" \
          -d '{"message": "✅ Task Succeeded : Monitoring BE Deployed to Production"}'
