name: Sensor Monitoring BE CI/CD

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Debug SSH Connection
      - name: Debug SSH Connection
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no -o LogLevel=DEBUG ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Connected"

      # 3. Sensor Monitoring BE CI/CD
      - name: Sensor Monitoring BE CI/CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "Navigating to the project directory..."
            cd /usr/go/sensor_monitoring_be
            
            echo "Pulling the latest code from the master branch..."
            git pull origin master
            
            echo "Cleaning up and updating Go modules..."
            go mod tidy
            
            echo "Building the Go application..."
            go build -o sensor_monitoring_be
            
            echo "Restarting the PM2 service..."
            pm2 restart sensor_monitoring_be
            
            echo "Deployment complete!"

      # 4. Send success notification via custom API
      - name: Send Telegram Notification
        if: success() # This step runs only if previous steps succeeded
        run: |
          echo "Sending success notification..."
          curl -s -X POST https://telebot.apicollection.my.id/api/v1/cicd/send-message \
          -H "Content-Type: application/json" \
          -d '{"message": "✅ Task Succeeded : Monitoring BE Deployed to Production"}'
